# Generated by Django 3.1.2 on 2020-11-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=100)),
                ('ideanid', models.CharField(max_length=100)),
                ('iinstrid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('sinstitute', models.CharField(max_length=100)),
                ('ssupervisor', models.CharField(max_length=100)),
                ('sphone', models.CharField(max_length=100)),
                ('spassword', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
                ('trole', models.CharField(max_length=100)),
                ('tphone', models.CharField(max_length=100)),
                ('tpassword', models.CharField(max_length=300)),
                ('tins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institute')),
            ],
        ),
    ]
