# Generated by Django 3.1.2 on 2020-11-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20201102_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='reqforleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('destin', models.CharField(max_length=300)),
                ('timestart', models.DateField()),
                ('timefinish', models.DateField()),
                ('process1', models.BooleanField(default=0)),
                ('process2', models.BooleanField(default=0)),
                ('process3', models.BooleanField(default=0)),
                ('is_finished', models.BooleanField(default=0)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stu')),
            ],
        ),
    ]
