# Generated by Django 3.1.2 on 2020-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveReq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqforleave',
            name='timefinish',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reqforleave',
            name='timestart',
            field=models.CharField(max_length=300),
        ),
    ]
